name: "Remove Multi File"
description: |
  Deletes a given file or folder in a cross-platform way. Succeeds even if there is
  no file at the requested path.
branding:
  icon: file
  color: red
inputs:
  path:
    default: ""
    required: true
    description: "multi line path to remove"
runs:
  using: 'node16'
  main: 'dist/index.js'
